# TODO: Translation updated at 2024-08-15 10:47

translate french strings:

    # game/screens/scroll/hunt_events.rpy:2
    old "The event now known as the Fall of Beacon was a watershed moment for the world. It shattered alliances, convictions, assumptions and the very bedrock of civilization on Remnant. Never before had Hunters and students been so targeted, not even during the Great War: for all the conflicts and disputes in history, the unspoken rule had always been to respect the independence and life of Hunters. Their mission served the greater good and benefited everyone, no matter the nation or race."
    new "L’événement désormais connu sous le nom de Chute de Beacon a été un moment décisif pour le monde. Cela a brisé des alliances, des convictions, des hypothèses et le fondement même de la civilisation sur Remnant. Jamais auparavant les chasseurs et les étudiants n'avaient été autant visés, même pendant la Grande Guerre : malgré tous les conflits et disputes de l'histoire, la règle tacite avait toujours été de respecter l'indépendance et la vie des chasseurs. Leur mission servait le bien commun et profitait à tous, quelle que soit la nation ou la race."

    # game/screens/scroll/hunt_events.rpy:3
    old "The White Fang shattered that rule: the attack used captive Grimm, they targeted civilians, Hunters and students alike, and if it weren't for the efforts of members of the latter group the Amity Arena would have fallen on Vale City, sending the number of casualities sky high. There are also rumours of a different nearby battle which, according to eyewitnesses, involved a Grimm the size of a literal mountain. The territory of Beacon Academy is now a no-man's zone overrun with Grimm, and the fallen Amity Arena is now a similarly grotesque relic."
    new "Le White Fang a brisé cette règle : l'attaque a utilisé des Grimms captifs, ils ont ciblé des civils, des chasseurs et des étudiants, et sans les efforts des membres de ce dernier groupe, l'Arène d'Amity serait tombée sur la ville de Vale, envoyant le numéro le nombre de victimes atteindre des sommets. Il y a aussi des rumeurs d'une autre bataille à proximité qui, selon des témoins oculaires, impliquait un Grimm de la taille d'une montagne. Le territoire de l'Académie de Beacon est désormais une zone interdite envahie par les Grimms, et l'Arène d'Amity déchue est désormais une relique tout aussi grotesque."

    # game/screens/scroll/hunt_events.rpy:4
    old "In the wake of the event, it was discovered that the White Fang didn't act alone: they had mysterious allies, even up to and including in the highest spheres of mistrali politics. The revelation landed Mistral in civil war as the trust between nations was broken, and so was the Network. It took Atlas an year to replace the connectivity lost with the transmission relay in the Tower of Beacon. In the process, the nation virtually overtook the running of the valesian chapter of the Hunters Organization and the capital of Vale, while its military gained significantly more influence internally."
    new "À la suite de l'événement, on a découvert que le White Fang n'agissait pas seul : ils avaient de mystérieux alliés, même dans les plus hautes sphères de la politique mistralienne. La révélation a plongé Mistral dans la guerre civile alors que la confiance entre les nations était brisée, comme son réseau. Il a fallu un an à Atlas pour remplacer la connectivité perdue avec le relais de transmission dans la Tour de Beacon. Dans le processus, la nation a pratiquement dépassé la direction de la section valésienne de l'Organisation des Chasseurs et la capitale de Vale, tandis que son armée a gagné beaucoup plus d'influence à l'intérieur."

    # game/screens/scroll/hunt_events.rpy:5
    old "Anti-faunus sentiments are at an all time high in Vale and Atlas both, and Menagerie has been forced to involve itself in international politics for the first time since its founding. Vacuo has similarly started taking a more pro-active stance in reaction to Atlas's increased international interventionism. Most surprising of all, though, was the development concerning the Beacon students and valesian Hunters who refused to be rolled into the new Atlas-ran structure. Taking possession of an once unclaimed piece of no-man's land in the Kingdom of Vale, they've founded a new nation, whose very existence is now already being called into question..."
    new "Les sentiments anti-fauni sont à un niveau sans précédent à Vale et à Atlas, et Ménagerie a été contrainte de s'impliquer dans la politique internationale pour la première fois depuis sa création. Vacuo a également commencé à adopter une position plus proactive en réaction à l'interventionnisme international accru d'Atlas. Le plus surprenant, cependant, fut la situation concernant les étudiants de Beacon et les chasseurs valésiens qui refusèrent d'être intégrés dans la nouvelle structure gérée par Atlas. Prenant possession d'un no man's land autrefois non réclamé dans le Royaume de Vale, ils ont fondé une nouvelle nation, dont l'existence même est déjà remise en question..."
