# TODO: Translation updated at 2024-08-15 10:47

translate french strings:

    # game/screens/scroll/hunt_entities.rpy:6
    old "The largest and most prominent international organization for the rights of fauni, the White Fang started out of a desire to coordinate at an international level all the smaller regional organizations and pool together their resources and intelligence. In their first form, under the guidance of Ghira and Kali Belladonna, the organization was mainly involved in non-violent protesting, lobbying, campaigning and political influencing. Through their original methods they won many battles, but they soon found a cunning and ruthless adversary in the Schnee Company."
    new "L'organisation internationale de défense des droits des fauni la plus grande et la plus importante, le White Fang, est née du désir de coordonner au niveau international toutes les petites organisations régionales et de mettre en commun leurs ressources et leurs renseignements. Dans sa première forme, sous la direction de Ghira et Kali Belladonna, l'organisation était principalement impliquée dans des manifestations non violentes, du lobbying, des campagnes et de l'influence politique. Grâce à leurs méthodes originales, ils gagnèrent de nombreuses batailles, mais ils trouvèrent bientôt un adversaire rusé et impitoyable en la Société Schnee."

    # game/screens/scroll/hunt_entities.rpy:7
    old "Tensions grew as the second generation in the company's leadership used their increasing wealth and influence to push for legislations which favoured the company and its executives while diminishing the rights of workers, particularly in sectors where the workforce was disproportionally made up of Fauni. Escalating tensions came to a head during the events of White Monday, where the peaceful protesters ultimately turned violent. Riding on that wave of growing resentment and the ultimate repeal of the hated legislation, the Belladonnas abdicated their position."
    new "Les tensions se sont accrues à mesure que la deuxième génération de dirigeants de la société a utilisé sa richesse et son influence croissantes pour faire pression en faveur de législations qui favorisaient l'entreprise et ses dirigeants tout en diminuant les droits des travailleurs, en particulier dans les secteurs où la main-d'œuvre était composée de manière disproportionnée de fauni. L'escalade des tensions a atteint son paroxysme lors des événements du White Monday, où les manifestants pacifiques sont finalement devenus violents. Surfant sur cette vague de ressentiment grandissant et sur l’abrogation définitive de la législation détestée, les Belladonna ont abdiqué leur position."

    # game/screens/scroll/hunt_entities.rpy:8
    old "The second generation leader of the Fang, Sienna Khan, brought upon a number of organizational reforms and increased the scope of activities of the Fang, forming an ever increasing militaristic branch which according to some may now be the second biggest army in Remnant. Protests and lobbying were joined by raids and bombings, and together they slowly started chipping away at the power and influence of the Schnee Company while also giving rise to an extremist fringe within the ranks of the Fang."
    new "La dirigeante de la deuxième génération du Fang, Sienna Khan, a introduit un certain nombre de réformes organisationnelles et a élargi la portée des activités du Fang, formant une branche militariste toujours croissante qui, selon certains, pourrait désormais être la deuxième plus grande armée de Remnant. Aux protestations et au lobbying s'ajoutèrent des raids et des attentats à la bombe, et ensemble, ils commencèrent lentement à réduire le pouvoir et l'influence de la Société Schnee tout en donnant naissance à une frange extrémiste dans les rangs du Fang."

    # game/screens/scroll/hunt_entities.rpy:9
    old "It's from this extremist fringe that arose Adam Taurus, the Butcher of Beacon. Riding on the clout and influence accrued through the Fall of Beacon, he ultimately completed a violent takeover of the Fang with an attempted assassination of Sienna Khan. Through his take-over, he also rang the death toll on the history of the Fang, planning to turn it into a new organization with new goals and methods beholden to his vision: the Red Fang."
    new "C'est de cette frange extrémiste qu'est né Adam Taurus, le Boucher de Beacon. S'appuyant sur sa réputation et son influence accumulées lors de la Chute de Beacon, il a finalement réalisé une violente prise de contrôle du Fang par une tentative d'assassinat de Sienna Khan. Grâce à sa prise de pouvoir, il a également fait le bilan de l'histoire du Fang, prévoyant d'en faire une nouvelle organisation avec de nouveaux objectifs et de nouvelles méthodes fidèles à sa vision : le Red Fang."

    # game/screens/scroll/hunt_entities.rpy:12
    old "As long as Grimm exist, so shall the Hunters. The role of someone trained in Aura and the use of their Semblance, tasked specifically with destroying Grimm and protecting humans and fauni from them, has existed as long as recorded history. The modern conception of the role is more recent, based on the structure of the Hunter Caste of Vacuo and the wealth of knowledge codified by Dorothea Grimm."
    new "Tant que les Grimms existeront, les chasseurs existeront aussi. Le rôle d'une personne formée à l'Aura et à l'utilisation de sa Semblance, chargée spécifiquement de détruire les Grimms et de protéger les humains et les fauni d'eux, existe depuis aussi longtemps que l'histoire est enregistrée. La conception moderne du rôle est plus récente, basée sur la structure de la Caste des Chasseurs de Vacuo et la richesse des connaissances codifiées par Dorothea Grimm."

    # game/screens/scroll/hunt_entities.rpy:13
    old "Following the Great War, the Hunters formed into an international organization with the task of fighting and containing the Grimm, plus nurture and raise the next generation of Hunters through academies of various level. If on principle separate and independent from Remnant's nations, the reality varies with the regional chapter. For example, in the more militarized Atlas the Hunter Chapter has high levels of integration with the army."
    new "Après la Grande Guerre, les Chasseurs se sont formés en une organisation internationale chargée de combattre et de contenir les Grimms, ainsi que de nourrir et d'élever la prochaine génération de chasseurs à travers des académies de différents niveaux. Si en principe ils sont séparés et indépendants des nations de Remnant, la réalité varie selon le chapitre régional. Par exemple, à Atlas, plus militarisée, le chapitre chasseur a des niveaux élevés d'intégration avec l'armée."

    # game/screens/scroll/hunt_entities.rpy:14
    old "The Fall of Beacon has brought major changes in the Valesian chapter, which ended up under Atlas's jurisdiction after the event. Not all Valesian Hunters were willing to acquiesce, including most of the staff of Beacon Academy. This resulted in a schism, further exacerbated by the recent declaration of independence by the City of Peak, established and founded by the Hunter diaspora which constitutes the backbone of its ruling class."
    new "La Chute de Beacon a apporté des changements majeurs dans le chapitre valésien, qui s'est retrouvé sous la juridiction d'Atlas après l'événement. Tous les chasseurs valésiens n’étaient pas disposés à acquiescer, y compris la plupart des membres du personnel de l'Académie de Beacon. Cela a abouti à un schisme, encore exacerbé par la récente déclaration d’indépendance de la Ville de Peak, établie et fondée par la diaspora chasseuse qui constitue l’épine dorsale de sa classe dirigeante."

    # game/screens/scroll/hunt_entities.rpy:19
    old "Grimm don't 'grow' in the traditional sense of the term. They don't weaken with age, their physical shape doesn't change for their entire life -barring damage- and none of their skills or abilities get stronger with time or usage, unless they survive long enough to suddenly change into a new form. This process seems to be completely dependent on the passage of time and also brings with it a change in behaviour."
    new "Les Grimms ne « grandissent » pas au sens traditionnel du terme. Ils ne s'affaiblissent pas avec l'âge, leur forme physique ne change pas de toute leur vie - sauf dommages - et aucune de leurs compétences ou capacités ne se renforce avec le temps ou l'utilisation, à moins qu'ils ne survivent assez longtemps pour se transformer soudainement en une nouvelle forme. Ce processus semble entièrement dépendant du temps qui passe et entraîne également un changement de comportement."

    # game/screens/scroll/hunt_entities.rpy:20
    old "The Grimm are divided in three Weight Classes -so called because of the debunked belief that Growth automatically netted an increase in size-: Normal, Great -also called Alphas- and Gargantuan. Needless to say, an increased weight class also means increased danger. If most Hunters can handle a Normal Grimm or even groups of them on their own, Great Grimm require more effort and careful strategy to take down. With careful planning and the right equipment, though, even groups of humans not trained in using Aura can take down a an Alpha."
    new "Les Grimms sont divisés en trois classes de poids - ainsi appelées en raison de la croyance démystifiée selon laquelle la croissance entraîne automatiquement une augmentation de taille - : Normal, Grand - également appelé Alphas - et Gargantuesque. Inutile de dire qu’une catégorie de poids plus élevée signifie également un danger accru. Si la plupart des chasseurs peuvent gérer seuls un Grimm normal ou même des groupes d'entre eux, les Grands Grimms nécessitent plus d'efforts et une stratégie prudente pour être éliminés. Avec une planification minutieuse et le bon équipement, même des groupes d'humains non formés à l'utilisation d'Aura peuvent éliminer un Alpha."

    # game/screens/scroll/hunt_entities.rpy:21
    old "Gargantuan Grimm instead require the combined effort and full might of multiple Hunters to be destroyed and their dangerousness varies wildly, depending on their abilities and the skills of those who would fell them. There have been Gargantuan Grimm taken out by just one team of four and others that have required the sacrifice of a dozen full fledged hunters to take down. Due to their territorial nature, though, they are much more manageable once identified and are usually left alone unless they directly endanger human settlements."
    new "Les Grimms Gargantuesques nécessitent plutôt l'effort combiné et la pleine puissance de plusieurs chasseurs pour être détruits et leur dangerosité varie énormément, en fonction de leurs capacités et des compétences de ceux qui voudraient les abattre. Il y a eu des Grimms Gargantuesques éliminés par une seule équipe de quatre et d'autres qui ont nécessité le sacrifice d'une douzaine de chasseurs à part entière pour être éliminés. Cependant, en raison de leur nature territoriale, ils sont beaucoup plus gérables une fois identifiés et sont généralement laissés seuls à moins qu’ils ne mettent directement en danger les établissements humains."

    # game/screens/scroll/hunt_entities.rpy:22
    old "The Fall of Beacon provided the first ever recorded appearance of a new class, the so called Primordial Grimm. Believed to be the progenitors, the first Grimm ever created, their sole role seems to be to stay hidden and keep recreating Grimm from wild Dark Matter, unless roused. Enviromental readings have then revealed that the Vale Area has seen a decrease in Grimm presence since the destruction of the local Primordial, code-name Kevin."
    new "La Chute de Beacon a fourni la toute première apparition enregistrée d'une nouvelle classe, les soi-disant Grimms Primordiaux. Considérés comme les ancêtres, les premiers Grimms jamais créés, leur seul rôle semble être de rester cachés et de continuer à recréer des Grimms à partir de la matière noire sauvage, à moins d'être réveillés. Des analyses environnementales ont ensuite révélé que la région de Vale a connu une diminution de la présence de Grimms depuis la destruction du Primordial local, nom de code Kevin."
